kadai_006/appenv_vgg16app/photoidentify/photoidentify/urls.py

from django.urls import path
from prediction.views import predict

urlpatterns = [
    path('', predict, name='predict'),
]

kadai_006/appenv_vgg16app/photoidentify/prediction/models.py
from django.db import models

# Create your models here.

kadai_006/appenv_vgg16app/photoidentify/prediction/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

kadai_006/appenv_vgg16app/photoidentify/prediction/views.py
from django.shortcuts import render
from .forms import ImageUploadForm
from django.conf import settings
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.applications.vgg16 import decode_predictions
from io import BytesIO
import os

def predict(request):
    if request.method == 'GET':
         form = ImageUploadForm()
         return render(request, 'home.html', {'form': form})       
    if request.method == 'POST':
         form = ImageUploadForm(request.POST, request.FILES)
         if form.is_valid():
             img_file = form.cleaned_data['image']
             img_file = BytesIO(img_file.read())
             img = load_img(img_file, target_size=(224, 224))
             img_array = img_to_array(img)
             img_array = img_array.reshape((1, 224, 224, 3))
             img_array = preprocess_input(img_array)
             model_path = os.path.join(settings.BASE_DIR, 'prediction', 'models', 'vgg16.h5')
             model = load_model(model_path)
             result = model.predict(img_array)
             prediction = decode_predictions(result)[0]
             img_data = request.POST.get('img_data')
             return render(request, 'home.html', {'form': form, 'prediction': prediction, 'img_data': img_data})
         else:
             form = ImageUploadForm()
             return render(request, 'home.html', {'form': form})

kadai_006/appenv_vgg16app/photoidentify/prediction/templates/home.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>画像判定アプリ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
  <div class="container py-5 text-center">
   <h2 class="mb-4">画像判定します</h2>
   <form method="post" enctype="multipart/form-data">
    <div class="mb-3">
     {% csrf_token %}
     {{ form.as_p }}
     <input id="img_data" type="hidden" name="img_data" />
    </div>
    <img id="preview" style="display: none;" class="img-fluid mb-3" />
    <br>
    <button type="submit" class="btn btn-primary btn-lg">判定</button>
   </form>

   {% if prediction %}
      <div id="prediction">
        <hr>
        <h2 class="mb-4">判定結果</h2>
        <p>あなたのアップロードした画像の判定結果は以下の通りです。</p>
        <img src="{{ img_data }}" class="img-fluid mb-3"> 
        <table class="table">
            <thead>
                <tr>
                    <th>カテゴリ</th>
                    <th>確率</th>
                </tr>
            </thead>
            {% for item in prediction %}
            <tr>
                <td>{{ item.1 }}</td>
                <td>{{ item.2 }} %</td>
            </tr>
            {% endfor %}
        </table>
      </div>
    {% endif %}
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
    $(function() {
        $('#id_image').on('change', function() {
        var reader = new FileReader();
        reader.onload = function () {
            $("#preview").attr('src', reader.result);
            $("#preview").show();
            $("#img_data").val(reader.result);
        }
        reader.readAsDataURL(this.files[0]);
        $("#prediction").text('');
        });
    });
  </script> 
</body>
</html>